// Package model provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package model

import (
	"encoding/json"
	"fmt"
	"time"
)

// Defines values for AgendaKind.
const (
	Deadline         AgendaKind = "deadline"
	Event            AgendaKind = "event"
	PastScheduled    AgendaKind = "past-scheduled"
	Scheduled        AgendaKind = "scheduled"
	UpcomingDeadline AgendaKind = "upcoming-deadline"
)

// Valid indicates whether the value is a known member of the AgendaKind enum.
func (e AgendaKind) Valid() bool {
	switch e {
	case Deadline:
		return true
	case Event:
		return true
	case PastScheduled:
		return true
	case Scheduled:
		return true
	case UpcomingDeadline:
		return true
	default:
		return false
	}
}

// Defines values for CreateTaskPriority.
const (
	CreateTaskPriorityA CreateTaskPriority = "A"
	CreateTaskPriorityB CreateTaskPriority = "B"
	CreateTaskPriorityC CreateTaskPriority = "C"
)

// Valid indicates whether the value is a known member of the CreateTaskPriority enum.
func (e CreateTaskPriority) Valid() bool {
	switch e {
	case CreateTaskPriorityA:
		return true
	case CreateTaskPriorityB:
		return true
	case CreateTaskPriorityC:
		return true
	default:
		return false
	}
}

// Defines values for CreateTaskRepeatToState.
const (
	CreateTaskRepeatToStateNEXT CreateTaskRepeatToState = "NEXT"
	CreateTaskRepeatToStateTODO CreateTaskRepeatToState = "TODO"
)

// Valid indicates whether the value is a known member of the CreateTaskRepeatToState enum.
func (e CreateTaskRepeatToState) Valid() bool {
	switch e {
	case CreateTaskRepeatToStateNEXT:
		return true
	case CreateTaskRepeatToStateTODO:
		return true
	default:
		return false
	}
}

// Defines values for CreateTaskState.
const (
	CreateTaskStateNEXT CreateTaskState = "NEXT"
	CreateTaskStateTODO CreateTaskState = "TODO"
)

// Valid indicates whether the value is a known member of the CreateTaskState enum.
func (e CreateTaskState) Valid() bool {
	switch e {
	case CreateTaskStateNEXT:
		return true
	case CreateTaskStateTODO:
		return true
	default:
		return false
	}
}

// Defines values for ProblemCode.
const (
	ProblemCodeConflict          ProblemCode = "conflict"
	ProblemCodeEngineUnavailable ProblemCode = "engine_unavailable"
	ProblemCodeForbidden         ProblemCode = "forbidden"
	ProblemCodeInternal          ProblemCode = "internal"
	ProblemCodeInvalid           ProblemCode = "invalid"
	ProblemCodeNotFound          ProblemCode = "not_found"
	ProblemCodeRateLimited       ProblemCode = "rate_limited"
	ProblemCodeUnauthorized      ProblemCode = "unauthorized"
)

// Valid indicates whether the value is a known member of the ProblemCode enum.
func (e ProblemCode) Valid() bool {
	switch e {
	case ProblemCodeConflict:
		return true
	case ProblemCodeEngineUnavailable:
		return true
	case ProblemCodeForbidden:
		return true
	case ProblemCodeInternal:
		return true
	case ProblemCodeInvalid:
		return true
	case ProblemCodeNotFound:
		return true
	case ProblemCodeRateLimited:
		return true
	case ProblemCodeUnauthorized:
		return true
	default:
		return false
	}
}

// Defines values for State.
const (
	StateCANCELLED State = "CANCELLED"
	StateDOING     State = "DOING"
	StateDONE      State = "DONE"
	StateNEXT      State = "NEXT"
	StateTODO      State = "TODO"
	StateWAITING   State = "WAITING"
)

// Valid indicates whether the value is a known member of the State enum.
func (e State) Valid() bool {
	switch e {
	case StateCANCELLED:
		return true
	case StateDOING:
		return true
	case StateDONE:
		return true
	case StateNEXT:
		return true
	case StateTODO:
		return true
	case StateWAITING:
		return true
	default:
		return false
	}
}

// Defines values for TaskPriority.
const (
	TaskPriorityA           TaskPriority = "A"
	TaskPriorityB           TaskPriority = "B"
	TaskPriorityC           TaskPriority = "C"
	TaskPriorityLessThanNil TaskPriority = "<nil>"
)

// Valid indicates whether the value is a known member of the TaskPriority enum.
func (e TaskPriority) Valid() bool {
	switch e {
	case TaskPriorityA:
		return true
	case TaskPriorityB:
		return true
	case TaskPriorityC:
		return true
	case TaskPriorityLessThanNil:
		return true
	default:
		return false
	}
}

// Defines values for TaskRepeatToState.
const (
	TaskRepeatToStateLessThanNil TaskRepeatToState = "<nil>"
	TaskRepeatToStateNEXT        TaskRepeatToState = "NEXT"
	TaskRepeatToStateTODO        TaskRepeatToState = "TODO"
)

// Valid indicates whether the value is a known member of the TaskRepeatToState enum.
func (e TaskRepeatToState) Valid() bool {
	switch e {
	case TaskRepeatToStateLessThanNil:
		return true
	case TaskRepeatToStateNEXT:
		return true
	case TaskRepeatToStateTODO:
		return true
	default:
		return false
	}
}

// Defines values for TransitionResultWarnings.
const (
	DoingLimitExceeded TransitionResultWarnings = "doing_limit_exceeded"
)

// Valid indicates whether the value is a known member of the TransitionResultWarnings enum.
func (e TransitionResultWarnings) Valid() bool {
	switch e {
	case DoingLimitExceeded:
		return true
	default:
		return false
	}
}

// Defines values for TransitionTaskParamsAction.
const (
	Cancel   TransitionTaskParamsAction = "cancel"
	Complete TransitionTaskParamsAction = "complete"
	Skip     TransitionTaskParamsAction = "skip"
	Start    TransitionTaskParamsAction = "start"
	Wait     TransitionTaskParamsAction = "wait"
)

// Valid indicates whether the value is a known member of the TransitionTaskParamsAction enum.
func (e TransitionTaskParamsAction) Valid() bool {
	switch e {
	case Cancel:
		return true
	case Complete:
		return true
	case Skip:
		return true
	case Start:
		return true
	case Wait:
		return true
	default:
		return false
	}
}

// AgendaEntry defines model for AgendaEntry.
type AgendaEntry struct {
	// Date Examples: 2026-10-25
	Date Date       `json:"date"`
	ID   *ID        `json:"id"`
	Kind AgendaKind `json:"kind"`

	// Task The task, or null for an event (an entry without a TODO state).
	Task  *Task  `json:"task"`
	Title string `json:"title"`
}

// AgendaInfo defines model for AgendaInfo.
type AgendaInfo struct {
	// Date Date of the timestamp that put the entry on the agenda.
	//
	// Examples: 2026-10-25
	Date Date       `json:"date"`
	Kind AgendaKind `json:"kind"`
}

// AgendaKind defines model for AgendaKind.
type AgendaKind string

// AgendaList defines model for AgendaList.
type AgendaList struct {
	Items []AgendaEntry `json:"items"`
}

// CreateTask defines model for CreateTask.
type CreateTask struct {
	// Body Free text. Stored so it cannot create Org structure; active timestamps are stored inactive.
	Body     *string             `json:"body,omitempty"`
	Deadline *TimestampInput     `json:"deadline,omitempty"`
	Priority *CreateTaskPriority `json:"priority,omitempty"`

	// ProjectID A level-1 heading in projects/; the task becomes its last child.
	ProjectID *ID `json:"project_id,omitempty"`

	// RepeatToState State a repeating task returns to after completion (default NEXT).
	RepeatToState *CreateTaskRepeatToState `json:"repeat_to_state,omitempty"`
	Scheduled     *TimestampInput          `json:"scheduled,omitempty"`
	State         *CreateTaskState         `json:"state,omitempty"`
	Tags          *[]string                `json:"tags,omitempty"`

	// Title One line. Must not start with a priority cookie (`[#A]`) or
	// `COMMENT`, nor end with a tag list (`:tag:`). Active timestamps
	// are stored inactive.
	Title string `json:"title"`
}

// CreateTaskPriority defines model for CreateTask.Priority.
type CreateTaskPriority string

// CreateTaskRepeatToState State a repeating task returns to after completion (default NEXT).
type CreateTaskRepeatToState string

// CreateTaskState defines model for CreateTask.State.
type CreateTaskState string

// Date Examples: 2026-10-25
type Date = string

// ID defines model for ID.
type ID = string

// Meta defines model for Meta.
type Meta struct {
	// CalendarTz Examples: Asia/Seoul
	CalendarTz    string `json:"calendar_tz"`
	DoingLimit    int    `json:"doing_limit"`
	EngineVersion string `json:"engine_version"`

	// Today Examples: 2026-10-25
	Today   Date   `json:"today"`
	Version string `json:"version"`
}

// Problem RFC 9457 problem details, with a stable machine-readable `code`.
type Problem struct {
	ActualState          *State                 `json:"actual_state,omitempty"`
	ActualVersion        *string                `json:"actual_version,omitempty"`
	Code                 ProblemCode            `json:"code"`
	Detail               string                 `json:"detail"`
	Status               int                    `json:"status"`
	Title                string                 `json:"title"`
	Type                 string                 `json:"type"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// ProblemCode defines model for Problem.Code.
type ProblemCode string

// ProjectRef defines model for ProjectRef.
type ProjectRef struct {
	ID    ID     `json:"id"`
	Title string `json:"title"`
}

// State defines model for State.
type State string

// Task defines model for Task.
type Task struct {
	// Agenda Present in agenda-based lists (today, overdue).
	Agenda *AgendaInfo `json:"agenda,omitempty"`
	Body   string      `json:"body"`

	// ClosedAt When the task was last closed (DONE or CANCELLED), UTC.
	ClosedAt *time.Time `json:"closed_at"`
	Deadline *Timestamp `json:"deadline"`
	ID       ID         `json:"id"`

	// LocationHint File the task is in, for debugging only. Not an identifier; do not rely on it.
	LocationHint  string             `json:"location_hint"`
	Priority      *TaskPriority      `json:"priority"`
	Project       *ProjectRef        `json:"project"`
	RepeatToState *TaskRepeatToState `json:"repeat_to_state"`
	Scheduled     *Timestamp         `json:"scheduled"`
	State         State              `json:"state"`
	Tags          []string           `json:"tags"`
	Title         string             `json:"title"`

	// Version Opaque; changes whenever the task's entry changes.
	Version string `json:"version"`
}

// TaskPriority defines model for Task.Priority.
type TaskPriority string

// TaskRepeatToState defines model for Task.RepeatToState.
type TaskRepeatToState string

// TaskList defines model for TaskList.
type TaskList struct {
	Items []Task `json:"items"`
}

// Timestamp A planning date in the calendar zone.
type Timestamp struct {
	// Date Examples: 2026-10-25
	Date Date `json:"date"`

	// Repeat Org repeater, e.g. `+1m`, `++1w`, `.+3d`.
	Repeat *string `json:"repeat"`
	Time   *string `json:"time"`

	// WarningDays Days before a deadline from which it shows as upcoming.
	WarningDays *int `json:"warning_days"`
}

// TimestampInput defines model for TimestampInput.
type TimestampInput struct {
	// Date Examples: 2026-10-25
	Date        Date    `json:"date"`
	Repeat      *string `json:"repeat,omitempty"`
	Time        *string `json:"time,omitempty"`
	WarningDays *int    `json:"warning_days,omitempty"`
}

// Transition defines model for Transition.
type Transition struct {
	ExpectedState State `json:"expected_state"`

	// ExpectedVersion The task's `version`; required for repeating tasks.
	ExpectedVersion *string `json:"expected_version,omitempty"`
}

// TransitionResult defines model for TransitionResult.
type TransitionResult struct {
	Task     Task                       `json:"task"`
	Warnings []TransitionResultWarnings `json:"warnings"`
}

// TransitionResultWarnings defines model for TransitionResult.Warnings.
type TransitionResultWarnings string

// Conflict RFC 9457 problem details, with a stable machine-readable `code`.
type Conflict = Problem

// EngineUnavailable RFC 9457 problem details, with a stable machine-readable `code`.
type EngineUnavailable = Problem

// Forbidden RFC 9457 problem details, with a stable machine-readable `code`.
type Forbidden = Problem

// Invalid RFC 9457 problem details, with a stable machine-readable `code`.
type Invalid = Problem

// NotFound RFC 9457 problem details, with a stable machine-readable `code`.
type NotFound = Problem

// RateLimited RFC 9457 problem details, with a stable machine-readable `code`.
type RateLimited = Problem

// TaskListWithAgenda defines model for TaskListWithAgenda.
type TaskListWithAgenda = TaskList

// Unauthorized RFC 9457 problem details, with a stable machine-readable `code`.
type Unauthorized = Problem

// GetAgendaParams defines parameters for GetAgenda.
type GetAgendaParams struct {
	// Date Calendar date; defaults to today in the instance calendar zone.
	Date *Date `form:"date,omitempty" json:"date,omitempty"`
}

// CreateTaskParams defines parameters for CreateTask.
type CreateTaskParams struct {
	// IdempotencyKey Retrying with the same key and body returns the original response
	// instead of creating another task (held in memory for 24 h).
	IdempotencyKey *string `json:"Idempotency-Key,omitempty"`
}

// ListCompletedTasksParams defines parameters for ListCompletedTasks.
type ListCompletedTasksParams struct {
	// Date Calendar date; defaults to today in the instance calendar zone.
	Date *Date `form:"date,omitempty" json:"date,omitempty"`
}

// ListOverdueTasksParams defines parameters for ListOverdueTasks.
type ListOverdueTasksParams struct {
	// Date Calendar date; defaults to today in the instance calendar zone.
	Date *Date `form:"date,omitempty" json:"date,omitempty"`
}

// ListTodayTasksParams defines parameters for ListTodayTasks.
type ListTodayTasksParams struct {
	// Date Calendar date; defaults to today in the instance calendar zone.
	Date *Date `form:"date,omitempty" json:"date,omitempty"`
}

// TransitionTaskParamsAction defines parameters for TransitionTask.
type TransitionTaskParamsAction string

// CreateTaskJSONRequestBody defines body for CreateTask for application/json ContentType.
type CreateTaskJSONRequestBody = CreateTask

// TransitionTaskJSONRequestBody defines body for TransitionTask for application/json ContentType.
type TransitionTaskJSONRequestBody = Transition

// Getter for additional properties for Problem. Returns the specified
// element and whether it was found
func (a Problem) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for Problem
func (a *Problem) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for Problem to handle AdditionalProperties
func (a *Problem) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["actual_state"]; found {
		err = json.Unmarshal(raw, &a.ActualState)
		if err != nil {
			return fmt.Errorf("error reading 'actual_state': %w", err)
		}
		delete(object, "actual_state")
	}

	if raw, found := object["actual_version"]; found {
		err = json.Unmarshal(raw, &a.ActualVersion)
		if err != nil {
			return fmt.Errorf("error reading 'actual_version': %w", err)
		}
		delete(object, "actual_version")
	}

	if raw, found := object["code"]; found {
		err = json.Unmarshal(raw, &a.Code)
		if err != nil {
			return fmt.Errorf("error reading 'code': %w", err)
		}
		delete(object, "code")
	}

	if raw, found := object["detail"]; found {
		err = json.Unmarshal(raw, &a.Detail)
		if err != nil {
			return fmt.Errorf("error reading 'detail': %w", err)
		}
		delete(object, "detail")
	}

	if raw, found := object["status"]; found {
		err = json.Unmarshal(raw, &a.Status)
		if err != nil {
			return fmt.Errorf("error reading 'status': %w", err)
		}
		delete(object, "status")
	}

	if raw, found := object["title"]; found {
		err = json.Unmarshal(raw, &a.Title)
		if err != nil {
			return fmt.Errorf("error reading 'title': %w", err)
		}
		delete(object, "title")
	}

	if raw, found := object["type"]; found {
		err = json.Unmarshal(raw, &a.Type)
		if err != nil {
			return fmt.Errorf("error reading 'type': %w", err)
		}
		delete(object, "type")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for Problem to handle AdditionalProperties
func (a Problem) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.ActualState != nil {
		object["actual_state"], err = json.Marshal(a.ActualState)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'actual_state': %w", err)
		}
	}

	if a.ActualVersion != nil {
		object["actual_version"], err = json.Marshal(a.ActualVersion)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'actual_version': %w", err)
		}
	}

	object["code"], err = json.Marshal(a.Code)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'code': %w", err)
	}

	object["detail"], err = json.Marshal(a.Detail)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'detail': %w", err)
	}

	object["status"], err = json.Marshal(a.Status)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'status': %w", err)
	}

	object["title"], err = json.Marshal(a.Title)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'title': %w", err)
	}

	object["type"], err = json.Marshal(a.Type)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'type': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}
